const MONTHS = 12;
const MINIMUM_BALANCE = 0;
const INDEX_OF_ZEROTH_INITIAL_OF_LOAN_AMOUNT = 0;
const MINIMUM_AVAILABLE_EMIS = 1;

module.exports = { MONTHS, MINIMUM_BALANCE, INDEX_OF_ZEROTH_INITIAL_OF_LOAN_AMOUNT, MINIMUM_AVAILABLE_EMIS };
